# Generated by Django 5.1.7 on 2025-03-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Токен"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Загрузите аватар", null=True, upload_to="profile_img/", verbose_name="Аватар"
            ),
        ),
    ]
