# Generated by Django 5.1.7 on 2025-03-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.CharField(blank=True, max_length=12, null=True, verbose_name="Телефон")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя пользователя"),
        ),
    ]
