# Generated by Django 5.1.7 on 2025-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_contact_alter_reservation_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(help_text="Введите имя", verbose_name="Имя сотрудника")),
                ("last_name", models.CharField(help_text="Введите фамилию", verbose_name="Фамилия сотрудника")),
                ("position", models.CharField(help_text="Введите дложность", verbose_name="Должность сотрудника")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="employees/", verbose_name="Фото сотрудника"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_food", models.CharField(blank=True, max_length=150, null=True, verbose_name="Блюдо")),
                ("item_drink", models.CharField(blank=True, max_length=150, null=True, verbose_name="Напиток")),
                ("price", models.IntegerField(blank=True, null=True, verbose_name="Цена блюда")),
                ("image", models.ImageField(upload_to="menu_images/", verbose_name="Фото блюда")),
                ("size", models.IntegerField(blank=True, null=True, verbose_name="Размер порции (в гр.)")),
                ("kcal", models.IntegerField(blank=True, null=True, verbose_name="Калорийность")),
                ("if_vegan", models.BooleanField(default=False, verbose_name="Вегетерианское блюдо")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="Название ресторана")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание ресторана")),
                ("background", models.TextField(blank=True, null=True, verbose_name="История ресторана")),
                ("mission_and_values", models.TextField(blank=True, null=True, verbose_name="Миссия и ценности")),
                (
                    "image_description",
                    models.ImageField(blank=True, null=True, upload_to="interior/", verbose_name="Фото ресторана"),
                ),
                (
                    "image_service",
                    models.ImageField(blank=True, null=True, upload_to="interior/", verbose_name="Фото услуг"),
                ),
                (
                    "image_background",
                    models.ImageField(blank=True, null=True, upload_to="interior/", verbose_name="Фото услуг"),
                ),
                (
                    "image_mission_and_values",
                    models.ImageField(blank=True, null=True, upload_to="interior/", verbose_name="Фото для миссии"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="Название услуги"),
                ),
                ("service_detail", models.TextField(blank=True, null=True, verbose_name="Описание услуги")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="service_img/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сервис",
                "verbose_name_plural": "Сервисы",
            },
        ),
    ]
