# Generated by Django 5.1.7 on 2025-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_employees_menu_restaurant_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="slogan",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Слоган ресторана"),
        ),
    ]
